const DefaultConfig = require('../Utility/Config');
const Arabic = {
 APP_NAME: 'حلول المستقبل - CRM',
 SUCCESS: {
  SUCCESS: 'نجاح',
  CREATED: 'تم الإنشاء',
  UPDATED: 'تم التحديث',
  DELETED: 'تم الحذف',
  NO_CHANGES: 'لا توجد تغييرات',
 },
 Notification: {
  PendingContract: 'لقد تم رفع العقد الابتدائي للعميل {CustomerName}',
  FinishedContract: 'لقد تم رفع العقد النهائي للعميل {CustomerName}',
  PaidContract: 'لقد تم تحويل العميل {CustomerName} إلى قسم الحسابات',
  TimeWarning:
   'يوجد مهمة غير منتهية بعد وتم انتهاء ثلثي مدة التنفيذ بالاسم ( {ConTaskName} )',
  ExpiredTask:
   'يوجد مهمة تم انتهاء مدة تنفيذها ولم تكتمل بعد بالاسم ( {ConTaskName} )',
  VerifiedSales: 'تم تحويل عميل الي المبيعات',
  VerifiedToAccountManger:
   'لقد تم تحويل العميل {CustomerName} إلى مدير الحساب',
  VerifiedTecnicalHead: 'لقد تم تحويل العميل {CustomerName} إلى القسم التقني ',
  VerifiedTeamLeader:
   'لقد تم تحويل العميل {CustomerName} إلى القسم  ( {Sections} )',
   VerifiedTecnicalSubHead:
   'لقد تم تحويل العميل {CustomerName} إلى القسم  ( {Sections} )',
  VerifiedToAgent: 'لقد تم تحويل العميل {CustomerName} إلى الايجنت',
  ConTaskCreate: 'تم انشاء المهمة {ConTaskName}',
  ConTaskUpdate: 'تم تحديث المهمة {ConTaskName}',
  ConTaskComplete: 'تم انهاء المهمة {ConTaskName}',
 },
 VALIDATION: {
  NOT_ALLOWED: 'الحقل ( {filed} ) غير مسموح',
  ALLOWED_DATE_ONLY: 'الحقل ( {filed} ) يجب أن يكون تاريخ',
  ALLOWED_ARRAY: 'الحقل ( {filed} ) يجب أن يكون مصفوفة',
  REQUIRED: {
   FromId: 'من مطلوب',
   ToId: 'الي مطلوب',
   InterestId: 'المعرف مطلوب',
   InterestName: 'الاسم مطلوب',
   // user -------------------------------------
   UserId: 'المعرف مطلوب',
   UserName: 'الاسم مطلوب',
   UserCompany: 'الشركة مطلوبة',
   UserJobTitle: 'المسمى الوظيفي مطلوب',
   UserEmail: 'البريد الإلكتروني مطلوب',
   UserPassword: 'كلمة المرور مطلوبة',
   UserCode: 'الكود مطلوب',
   UserRoleId: 'الدور مطلوب',
   UserBranchId: 'الفرع مطلوب',
   UserStartDate: 'تاريخ البدء مطلوب',
   UserStatusId: 'الحالة مطلوبة',
   UserSectionId: 'القسم مطلوب',
   UserSubSectionId: 'القسم الفرعي مطلوب',
   NitchId: 'المجال مطلوب',
   SectionId: 'القسم مطلوب',
   StatusId: 'الحالة مطلوبة',
   PackageId: 'الحزمة مطلوبة',
   NitchName: 'الاسم مطلوب',
   ProductTypeId: 'نوع المنتج مطلوب',
   ProductTypeName: 'الاسم مطلوب',
   ContactWayId: 'طريقة الاتصال مطلوبة',
   ContactWayName: 'الاسم مطلوب',
   SectionName: 'الاسم مطلوب',
   StatusName: 'الاسم مطلوب',
   PackageName: 'الاسم مطلوب',
   SubSectionId: 'القسم الفرعي مطلوب',
   SubSectionSectionId: 'القسم مطلوب',
   SubSectionName: 'الاسم مطلوب',
   SubSectionKey: 'المفتاح مطلوب',
   SubSectionSubName: 'الاسم مطلوب',
   PackageName: 'الاسم مطلوب',
   Method: 'البريد الإلكتروني أو الكود مطلوب',
   Password: 'كلمة المرور مطلوبة',
   // ----------------- Customer -----------------
   CustomerId: 'العميل مطلوب',
   CustomerDataSource: 'مصدر الداتا مطلوب',
   CustomerCountry: 'البلد مطلوب',
   CustomerAdress: 'العنوان مطلوب',
   CustomerName: 'الاسم مطلوب',
   CustomerPhoneNumber: 'رقم الهاتف مطلوب',
   CustomerPhoneNumber2: 'رقم الهاتف 2 مطلوب',
   CustomerEmail: 'البريد الإلكتروني مطلوب',
   CustomerUrl: 'الرابط مطلوب',
   CustomerType: 'النوع مطلوب',
   CustomerWorkType: 'نوع العمل مطلوب',
   CustomerStatus: 'الحالة مطلوبة',
   CustomerContactWayId: 'طريقة الاتصال مطلوبة',
   CustomerNitchId: 'المجال مطلوب',
   CustomerCreatedById: 'تم الإنشاء بواسطة مطلوب',
   CustomerClassificationId: 'التصنيف مطلوب',
   CustomerInterestId: 'اهتمامات العميل مطلوب',
   CustomerProductTypeId: 'نوع المنتج مطلوب',
   CustomerResPosition: 'الموضع المطلوب مطلوب',
   CustomerFollowUpStatus: 'حالة المتابعة مطلوبة',
   CustomerFollowUpDate: 'تاريخ المتابعة مطلوب',
   HistoryContractId: 'العقد مطلوب',
   HistoryPosition: 'الموضع للشهر القادم مطلوب',
   HistoryDate: 'تاريخ الموضع للشهر القادم مطلوب',

   //    Classification Data
   ClassificationId: 'التصنيف مطلوب',
   ClassificationName: 'الاسم مطلوب',
   ClassificationCode: 'الكود مطلوب',
   File: 'الملف مطلوب',
   //    Contract
   ContractSalesId: 'المبيعات مطلوبة',
   ContractCustomerId: 'العميل مطلوب',
   ContractSalesDate: 'تاريخ المبيعات مطلوب',
   ContractEntryDate: 'تاريخ الإدخال مطلوب',
   ContractTaskName: 'اسم المهمة مطلوب',

   //  Sales contract data
   ContractStandUp: 'الموقف مطلوب',
   ContractStandUpDate: 'تاريخ الموقف مطلوب',
   ContractInvoice: 'الفاتورة مطلوبة',
   ContractPayDate: 'تاريخ الدفع مطلوب',
   ContractAmmount: 'المبلغ مطلوب',
   ContractPaidMonthes: 'الشهور المدفوعة مطلوبة',
   //  Another contract Data
   ContractTimeRecives: 'وقت الاستلام مطلوب',
   ContractPhoneNumber: 'رقم الهاتف مطلوب',
   //    contract Notes
   ContractSalesPref: 'البريف النهائي للمبيعات مطلوبة',
   ContractCustomarNote: 'ملاحظات تخص العميل مطلوبة',
   ContractCustomarFeedback: 'فيدباك العميل مطلوبة',
   ContractCustomarPref: 'بريف العميل مطلوبة',
   ContractTecnicalSeoTeamLeaderPref: 'البريف مطلوب',
   ContractTecnicalOtherTeamLeaderPref: 'البريف مطلوب',
   ContractTecnicalSocialTeamLeaderPref: 'البريف مطلوب',
   ContractTecnicalAdsTeamLeaderPref: 'البريف مطلوب',
   ContractTecnicalHeadPref: 'البريف مطلوب',
   //
   RolePermissions: 'الأذونات مطلوبة',
   RoleName: 'الاسم مطلوب',
   RoleId: 'الدور مطلوب',
   //    Conntract Task
   ConTaskId: 'المهمة مطلوبة',
   ConTaskName: 'الاسم مطلوب',
   ConTaskSection: 'القسم مطلوب',
   ConTaskStart: 'تاريخ البدء مطلوب',
   ConTaskEnd: 'تاريخ الانتهاء مطلوب',
   ConTaskContractId: 'العقد مطلوب',

   ConSubTaskName: 'الاسم مطلوب',
   ConSubTaskValue: 'الوصف مطلوب',
   ConSubTaskEnd: 'تاريخ الانتهاء مطلوب',
   ConSubTaskTaskId: 'المهمة مطلوبة',
   ConSubTaskId: 'المهمة مطلوبة',

   Type: 'الأقسام مطلوبة',
  },
  CUSTOM: {
   // ----------------- user -----------------
   UserRoleId: `الدور يجب أن يكون واحد من (${DefaultConfig.ALLOWED_USER_ROLE})`,
   UserPassword: 'كلمة المرور يجب أن تكون على الأقل 6 أحرف',
   UserVrifyTypes: `نوع التحقق يجب أن يكون واحد ("Online", "Offline")`,
   CustomerType: `النوع يجب أن يكون واحد من (${DefaultConfig.ALLOWED_CUSTOMER_TYPES})`,
   Action: `الإجراء يجب أن يكون واحد من (${DefaultConfig.ALLOWED_CONTRACT_VERIFY_TYPES})`,
  },
  PATTERN: {},
 },
 ERRORS: {
  ADMIN_LETH_THAN_ONE: 'لا يمكنك تنفيذ هذه الأجراء لوجود مشرف واحد فقط',
  CONTRACT_LENGTH_ZERO: 'لا يوجد عقود متوفرة',
  INVALID_ACTION: 'نأسف لا يمكن تنفيذ هذا الإجراء',
  INVALID_SECTION: 'نأسف القسم غير صحيح',
  SAME_USER:
   'اجراء غير صحيح لا يمكن تحويل البينات الي نفس المستخدم  يرجي اختيار مستخدم اخر',
  TEAM_CAN_NOT_BE_ASSIGNED: 'لا يمكن تعيين قائد فريق اخر ',
  ACCOUNT_NOT_FOUND: 'لا يوجد حسابات رئيسية في الفرع يرجي الاتصال بالمشرف',
  ACCOUNT_MANAGER_NOT_FOUND:
   'لا يوجد مديرين الحسابات في الفرع يرجي الاتصال بالمشرف',
  TECNICAL_HEAD_NOT_FOUND:
   'لا يوجد مديرين تقنيين في الفرع يرجي الاتصال بالمشرف',
  INVALID_END_DATE: 'تاريخ الانتهاء لا يمكن ان يكون اقل من تاريخ اليوم',
  CUSTOMER_DISALLOWED: 'نأسف لا يمكن تعديل هذا العميل الا من خلال المشرف',
  INVALID_START_DATE: 'تاريخ البدء لا يمكن ان يكون اقل من تاريخ اليوم',
  USER_IS_DISABLED: 'نأسف حسابك معطل. يرجي الاتصال بالمشرف',
  USER_HAS_ACTIONS: 'نأسف لا يمكن حذف هذا المستخدم لأنه يحتوي على قيود',
  ROUTE_NOT_FOUND: 'المسار غير موجود',
  ORIGIN_NOT_ALLOWED: 'اتصال غير مسموح به',
  BAD_REQUEST: 'بيانات غير صحيحة',
  NO_TOKEN: 'لم يتم تقديم رمز',
  CMD_NOT_FOUND: 'الأمر غير موجود',
  USER_NOT_FOUND: 'المستخدم غير موجود او ربما تم حذفه',
  SECTION_NOT_FOUND: 'القسم غير موجود او ربما تم حذفه',
  STATUS_NOT_FOUND: 'الحالة غير موجودة او ربما تم حذفه',
  PACKAGE_NOT_FOUND: 'الحزمة غير موجودة او ربما تم حذفه',
  BRANCH_NOT_FOUND: 'الفرع غير موجودة او ربما تم حذفه',
  NITCH_NOT_FOUND: 'المجال غير موجود او ربما تم حذفه',
  INTEREST_NOT_FOUND: 'اهتمامات العميل غير موجود او ربما تم حذفه',
  TEAM_NOT_FOUND: 'الفريق غير موجود او ربما تم حذفه',
  PRODUCT_TYPE_NOT_FOUND: 'نوع المنتج غير موجودة او ربما تم حذفه',
  CONTACT_WAY_NOT_FOUND: 'وسيلة الاتصال غير موجودة او ربما تم حذفه',
  PLATFORM_NOT_FOUND: 'المنصة غير موجودة او ربما تم حذفه',
  CONTRACT_TASK_NOT_FOUND: 'المهمة غير موجودة او ربما تم حذفه',
  CUSTOMER_NOT_FOUND: 'العميل غير موجود او ربما تم حذفه',
  CONTRACT_NOT_FOUND: 'العقد غير موجود او ربما تم حذفه',
  CLASSIFICTION_NOT_FOUND: 'التصنيف غير موجود او ربما تم حذفه',
  Notification_NOT_FOUND: 'الإشعار غير موجود او ربما تم حذفه',
  FILE_NOT_FOUND:
   ' الملف غير موجود ربما يكون هناك مشكلة في الحصول عليه يرجي الاتصال بالمشرف',
  ROLE_NOT_FOUND: 'الدور غير موجود او ربما تم حذفه',
  TYPE_NOT_FOUND: 'النوع غير مسموح',
  CONTRACT_ALREADY_COMPLETED:
   'لا يمكن إكمال هذا الإجراء لأن العقد قد انتهى بالفعل',
  CUSTOMER_HAVE_CONTRACTS: 'لا يمكن حذف العميل لأنه لديه عقود',
  CONTRACT_MISSING_PENDING: 'لا يمكن تحميل الملف في غياب عقد تمهيدي',
  USER_EXIST: 'المستخدم موجود بالفعل',
  USER_EMAIL_EXIST: 'البريد الإلكتروني موجود بالفعل',
  USER_NOT_ALLOWED_TO_USE_SERVICE:
   'نأسف لذلك ولكن ربما يكون حسابك تم حذفه يرجي الاتصال بالمشرف',
  USER_HAS_CONTRACTS: 'لا يمكن حذف المستخدم لأنه لديه عقود',
  SECTION_EXIST: 'القسم موجود بالفعل',
  STATUS_EXIST: 'الحالة موجودة بالفعل',
  PACKAGE_EXIST: 'الحزمة موجودة بالفعل',
  BRANCH_EXIST: 'الفرع موجودة بالفعل',
  NITCH_EXIST: 'المجال موجود بالفعل',
  INTEREST_EXIST: 'اهتمامات العميل موجود بالفعل',
  TEAM_EXIST: 'الفريق موجود بالفعل',
  PRODUCT_TYPE_EXIST: 'نوع المنتج موجود بالفعل',
  CONTACT_WAY_EXIST: 'نوع المنتج موجود بالفعل',
  PLATFOTM_EXIST: 'المنصة موجودة بالفعل',
  CUSTOMER_EXIST: 'العميل موجود بالفعل',
  CONTRACT_EXIST: 'العقد موجود بالفعل',
  CLASSIFICTION_EXIST: 'التصنيف موجود بالفعل',
  FILE_EXIST: 'الملف موجود بالفعل',
  ROLE_EXIST: 'الدور موجود بالفعل',

  INCORRECT_PASSWORD: 'كلمة المرور أو البريد الإلكتروني أو الكود غير صحيح',
  INCORRECT_OLD_PASSWORD: 'كلمة المرور القديمة غير صحيحة',
  INCORRECT_CODE: 'الكود أو البريد الإلكتروني غير صحيح',

  UserCode: 'الكود موجود بالفعل',
  UserEmail: 'البريد الإلكتروني موجود بالفعل',
  UserName: 'الاسم موجود بالفعل',
  SERVER_ERROR: 'خطأ داخلي في الخادم',
 },
};

module.exports = Arabic;
