const DefaultConfig = require('../Utility/Config');
const English = {
 APP_NAME: 'Future Solutions - Crm',
 SUCCESS: {
  SUCCESS: 'Success',
  CREATED: 'Created',
  UPDATED: 'Updated',
  DELETED: 'Deleted',
  NO_CHANGES: 'No Changes',
 },
 Notification: {
  PendingContract:
   'The Initial Contract For Client {CustomerName} Has Been Submitted.',
  FinishedContract:
   'The Final Contract For Client {CustomerName} Has Been Submitted.',
  PaidContract:
   'The Client {CustomerName} Has Been Transferred To The Accounts Department',
  TimeWarning:
   'There Is An UnFinished Task And Two-Thirds Of The Execution Time Has Expired With The Name ( {ConTaskName} )',
  ExpiredTask:
   'There Is An Expired Unfinished Task With The Name ( {ConTaskName} )',
  VerifiedSales: 'New Client Has Been Transferred To The Sales',
  //  Verified To Account Manger
  VerifiedToAccountManger:
   'The Client {CustomerName} Has Been Transferred To The Account Manger',
  VerifiedTecnicalHead:
   'The Client {CustomerName} Has Been Transferred To The Technical',
  VerifiedTeamLeader:
   "The Client {CustomerName} Has Been Transferred To The ( {Sections} ) Section Team Leader's",
  VerifiedTecnicalSubHead:
   'The Client {CustomerName} Has Been Transferred To The ( {Sections} ) Section',
  VerifiedToAgent:
   'The Client {CustomerName} Has Been Transferred To The Agent',
  ConTaskCreate: 'The Task {ConTaskName} Has Been Created',
  ConTaskUpdate: 'The Task {ConTaskName} Has Been Updated',
  ConTaskComplete: 'The Task {ConTaskName} Has Been Completed',
 },
 VALIDATION: {
  NOT_ALLOWED: 'Filed ( {filed} ) Is Not Allowed',
  ALLOWED_DATE_ONLY: 'Filed ( {filed} )  Must Be Date',
  ALLOWED_ARRAY: 'Filed ( {filed} )  Must Be Array',
  REQUIRED: {
   FromId: 'From Required',
   ToId: 'To Required',
   InterestId: 'Id Required',
   InterestName: 'Name Required',
   // user -------------------------------------
   UserId: 'Id Required',
   UserName: 'Name Required',
   UserCompany: 'Company Required',
   UserJobTitle: 'Job Title Required',
   UserEmail: 'Email Required',
   UserPassword: 'Password Required',
   UserCode: 'Code Required',
   UserRoleId: 'Role Required',
   UserBranchId: 'Branch Required',
   UserStartDate: 'Start Date Required',
   UserStatusId: 'Status Required',
   UserSectionId: 'Section Required',
   UserSubSectionId: 'Sub Section Required',
   NitchId: 'Nitch Required',
   SectionId: 'Section Required',
   StatusId: 'Status Required',
   PackageId: 'Package Required',
   NitchName: 'Name Required',
   ProductTypeId: 'Type Required',
   ProductTypeName: 'Name Required',
   ContactWayId: 'Contact Way Required',
   ContactWayName: 'Name Required',
   SectionName: 'Name Required',
   StatusName: 'Name Required',
   PackageName: 'Name Required',
   SubSectionId: 'Sub Section Required',
   SubSectionSectionId: 'Section Required',
   SubSectionName: 'Name Required',
   SubSectionKey: 'Key Required',
   SubSectionSubName: 'Name Required',
   PackageName: 'Name Required',
   Method: 'UserEmail Or UserCode Required',
   Password: 'Password Is Required',
   // ----------------- Customer -----------------
   CustomerId: 'Customer Required',
   CustomerDataSource: 'Date Source Required',
   CustomerCountry: 'Country Required',
   CustomerAdress: 'Adress Required',
   CustomerName: 'Name Required',
   CustomerPhoneNumber: 'Phone Number Required',
   CustomerPhoneNumber2: 'Phone Number 2 Required',
   CustomerEmail: 'Email Required',
   CustomerUrl: 'Url Required',
   CustomerType: 'Type Required',
   CustomerWorkType: 'Work Type Required',
   CustomerStatus: 'Status Required',
   CustomerContactWayId: 'Contact Way Required',
   CustomerNitchId: 'Nitch Required',
   CustomerCreatedById: 'Created By Required',
   CustomerProductTypeId: 'Product Type Required',
   CustomerClassificationId: 'Classification Required',
   CustomerInterestId: 'Customer Interest Required',
   CustomerResPosition: 'Res Position Required',
   CustomerFollowUpDate: 'Follow Up Date Required',
   CustomerFollowUpStatus: 'Follow Up Status Required',
   HistoryContractId: 'Contract Required',
   HistoryPosition: 'Next Month Position Required',
   HistoryDate: 'Next Month Position Date Required',

   //    Classification Data
   ClassificationId: 'Classification Required',
   ClassificationName: 'Name Required',
   ClassificationCode: 'Code Required',
   File: 'File Required',
   //    Contract
   ContractSalesId: 'Sales Required',
   ContractCustomerId: 'Customer Required',
   ContractSalesDate: 'Sales Date Required',
   ContractEntryDate: 'Entry Date Required',
   ContractTaskName: 'Task Name Required',
   //    contract Notes
   ContractSalesPref: 'Sales Pref Required',
   ContractCustomarNote: 'Customar Note Required',
   ContractCustomarFeedback: 'Customar Feedback Required',
   ContractCustomarPref: 'Customar Pref Required',
   //  Sales contract data
   ContractStandUp: 'Stand Up Required',
   ContractStandUpDate: 'Stand Up Date Required',
   ContractInvoice: 'Invoice Required',
   ContractPayDate: 'Pay Date Required',
   ContractAmmount: 'Ammount Required',
   ContractPaidMonthes: 'Paid Monthes Required',
   //  Another contract Data
   ContractTimeRecives: 'Time Recives Required',
   ContractPhoneNumber: 'Phone Number Required',
   ContractTecnicalSeoTeamLeaderPref: 'Pref Required',
   ContractTecnicalSocialTeamLeaderPref: 'Pref Required',
   ContractTecnicalAdsTeamLeaderPref: 'Pref Required',
   ContractTecnicalOtherTeamLeaderPref: 'Pref Required',
   ContractTecnicalHeadPref: 'Pref Required',
   //
   RolePermissions: 'Permissions Required',
   RoleName: 'Name Required',
   RoleId: 'Role Required',
   //    Conntract Task
   ConTaskId: 'Task Required',
   ConTaskName: 'Name Required',
   ConTaskSection: 'Section Required',
   ConTaskStart: 'Start Date Required',
   ConTaskEnd: 'End Date Required',
   ConTaskContractId: 'Contract Required',

   ConSubTaskName: 'Name Required',
   ConSubTaskValue: 'Description Required',
   ConSubTaskEnd: 'End Date Required',
   ConSubTaskTaskId: 'Task Required',
   ConSubTaskId: 'Task Required',

   Type: 'Sections Required',
  },
  CUSTOM: {
   // ----------------- user -----------------
   UserRoleId: `Role must be one of (${DefaultConfig.ALLOWED_USER_ROLE})`,
   UserPassword: 'Password must be at least 6 characters',
   UserVrifyTypes: `Verify Type must be one of ("Online", "Offline")`,
   CustomerType: `Type must be one of (${DefaultConfig.ALLOWED_CUSTOMER_TYPES})`,
   Action: `Action must be one of (${DefaultConfig.ALLOWED_CONTRACT_VERIFY_TYPES})`,
   INVALID_ACTION: 'Sorry, This Accion Is Not Allowed',
  },
  PATTERN: {},
 },
 ERRORS: {
  ADMIN_LETH_THAN_ONE:
   "You Cant't Do This Action Because There Is Only One Admin",
  CONTRACT_LENGTH_ZERO: 'There Are No Contract',
  INVALID_ACTION: 'Sorry, This Accion Is Not Allowed',
  INVALID_SECTION: 'Sorry, This Section Is Not Allowed',
  SAME_USER: 'You Cant Convert Data To Same User Please Choose Another User',
  TEAM_CAN_NOT_BE_ASSIGNED: 'Sorry, Team Can Have Only One TeamLeader',
  ACCOUNT_NOT_FOUND:
   'There Are No Head Account In The Branch  Please Contact The Administrator',
  ACCOUNT_MANAGER_NOT_FOUND:
   'There Are No Account Manager In The Branch Please Contact The Administrator',
  TECNICAL_HEAD_NOT_FOUND:
   'There Are No TECNICAL HEAD In The Branch Please Contact The Administrator',
  INVALID_END_DATE: 'End Date Cannot Be Leth Than Today',
  CUSTOMER_DISALLOWED:
   'Sorry, This Client Can Only Be Modified By The Administrator.',
  USER_HAS_ACTIONS: "Sorry, You Can't Delete This User Because It Has Actions.",
  INVALID_START_DATE: 'Start Date Cannot Be Leth Than Today',
  USER_IS_DISABLED:
   'Sorry Your Account Is Disabled. Please Contact The Administrator',
  ROUTE_NOT_FOUND: 'Route Not Found',
  ORIGIN_NOT_ALLOWED: 'No Allowed Connection',
  NO_TOKEN: 'No Token Provided',
  BAD_REQUEST: 'Invalid Data',
  CMD_NOT_FOUND: 'Command Not found',
  USER_NOT_FOUND: 'User Not Found Or May Be Deleted',
  SECTION_NOT_FOUND: 'Section Not Found Or May Be Deleted',
  STATUS_NOT_FOUND: 'Status Not Found Or May Be Deleted',
  PACKAGE_NOT_FOUND: 'Package Not Found Or May Be Deleted',
  BRANCH_NOT_FOUND: 'Branch Not Found Or May Be Deleted',
  NITCH_NOT_FOUND: 'Nitch Not Found Or May Be Deleted',
  INTEREST_NOT_FOUND: 'Interest Not Found Or May Be Deleted',
  TEAM_NOT_FOUND: 'Team Not Found Or May Be Deleted',
  PRODUCT_TYPE_NOT_FOUND: 'Product Type Not Found Or May Be Deleted',
  CONTACT_WAY_NOT_FOUND: 'Contact Way Not Found Or May Be Deleted',
  CONTRACT_TASK_NOT_FOUND: 'Task Not Found Or May Be Deleted',
  CUSTOMER_NOT_FOUND: 'Customer Not Found Or May Be Deleted',
  CONTRACT_NOT_FOUND: 'Contract Not Found Or May Be Deleted',
  CLASSIFICTION_NOT_FOUND: 'Classification Not Found Or May Be Deleted',
  Notification_NOT_FOUND: 'Notification Not Found Or May Be Deleted',
  FILE_NOT_FOUND:
   'The File Does Not Exist. There May Be a Problem Obtaining It. Please Contact The Administrator',
  ROLE_NOT_FOUND: 'Role Not Found Or May Be Deleted',
  TYPE_NOT_FOUND: 'Type Not Allowed',
  CONTRACT_ALREADY_COMPLETED:
   "This Action Can't Be Finish Because The Contract Is Already Finish",
  CUSTOMER_HAVE_CONTRACTS: "Customer Can't Be Deleted Because It Has Contracts",
  CONTRACT_MISSING_PENDING:
   'The File Cannot Be Uploaded In The Absence Of a Preliminary Contract',
  USER_EXIST: 'User Already Exist',
  USER_EMAIL_EXIST: 'Email Already Exist',
  USER_NOT_ALLOWED_TO_USE_SERVICE:
   'Sorry But May Be Your Account Deleted. Please Contact The Administrator',
  USER_HAS_CONTRACTS: "User Can't Be Deleted Because It Has Contracts",
  SECTION_EXIST: 'Section Already Exist',
  STATUS_EXIST: 'Status Already Exist',
  PACKAGE_EXIST: 'Package Already Exist',
  NITCH_EXIST: 'Nitch Already Exist',
  BRANCH_EXIST: 'Branch Already Exist',
  INTEREST_EXIST: 'Interest Already Exist',
  TEAM_EXIST: 'Team Already Exist',
  PRODUCT_TYPE_EXIST: 'Product Type Already Exist',
  CONTACT_WAY_EXIST: 'Product Type Already Exist',
  CONTRACT_TASK_EXIST: 'Task Already Exist',
  CUSTOMER_EXIST: 'Customer Already Exist',
  CONTRACT_EXIST: 'Contract Already Exist',
  CLASSIFICTION_EXIST: 'Classification Already Exist',
  FILE_EXIST: 'File Already Exist',
  ROLE_EXIST: 'Role Already Exist',

  INCORRECT_PASSWORD: 'Incorrect Password or Email or Code',
  INCORRECT_OLD_PASSWORD: 'Incorrect Old Password',
  INCORRECT_CODE: 'Incorrect Code or Email',
  UserCode: 'Code Is Already Exist',
  UserEmail: 'Email Is Already Taken',
  UserName: 'Name Is Already Taken',
  SERVER_ERROR: 'Internal Server Error',
 },
};
module.exports = English;
