const APP_NAME = "حلول المستقبل";
const Language = {
  APP_NAME: APP_NAME,
  NO_INTERNET: "لا يوجد اتصال بالإنترنت",
  CHECK_DATA: "جارٍ التحقق من البيانات، يرجى الانتظار...",
  NEED_RELOGIN: "تحتاج إلى إعادة تسجيل الدخول",
  NO_DATA: "لم يتم العثور على بيانات",
  No_AGENTS: "لا يوجد موظفين لهذا العقد",
  PERPARING: "جارٍ الإعداد",
  PERPARE: "إعداد",
  READY: "تجهيز",
  ACTIONS: "إجراءات",
  CONVERT_DATA: "تحويل البيانات",
  SETTINGS: "الاعدادات",
  CANCEL: "الغاء",
  SAVE: "حفظ",
  ADD: "اضافة جديد",
  UPDATE: "تحديث",
  EDIT: "تعديل",
  VERIFY: "الموافقة",
  DELETE: "حذف",
  CONFIRM: "تاكيد",
  COMPLETE: "اكمال",
  TASKS: "المهمات الفرعية",
  SHOW: "اظهار",
  SEARCH: "  ... بحث",
  SUCCESS: "تمت العملية بنجاح",
  UPLOAD: "تحميل ملف",
  UP: "رفع ملف",
  SYNC: "مزامنة البيانات",
  SYNCED: "تمت مزامنة البيانات بنجاح",
  DOWNLOAD: "تحميل الملف",
  PRINT: "طباعة",
  EXPORT: "تصدير",
  REFRESH: "تحديث البيانات",
  FILTER: "البحث",
  DEV_TOOLS: "الاجراءات الخارجية ليست مسموحة",
  DELETE_CONFIRM:
    "هل أنت متأكد أنك تريد الحذف؟ \n لا يمكنك التراجع عن هذه العملية",
  VERIFY_CONFIRM: "هل أنت متأكد؟ \n لا يمكنك التراجع عن هذه العملية",
  SERVER_ERROR: "فشل جلب البيانات من الخادم",
  CANCEL_DELETE: "الغاء الحذف",
  LIMIT: "الحد",
  REDIRECT_AFTER:
    "سيتم توجيهك إلى الصفحة الرئيسية بعد {Seconds_replacer} ثانية",
  PAGINATION_1: "الصفحة {page} من {total}",
  PAGINATION_2: "عرض {count} من {total} عنصر",
  NO_FILE_PREVIEW: "لا يمكن معاينة هذا النوع من الملفات، قم بتنزيله",
  NOTIFACTIONS: "الاشعارات",
  NOTIFACTION_MSG: "لديك اشعار جديد",
  NO_PERMISSION: "ليس لديك إذن للوصول إلى هذه الصفحة",
  NO_ANY_PERMISSION: "لا يمكن لدورك الوصول إلى أي صفحة، يرجى الاتصال بالمسؤول",
  TYPE: "النوع",
  NOTES: "ملاحظات",
  PAGE_NOT_FOUND: "الصفحة غير موجودة",
  BACK: "رجوع",
  SELECTED: "محدد",
  Density: "حجم الجدول",
  CONTRACT_NOT_PAID: "يجب أن تكون العقد مدفوعة قبل رفع العقد",
  Sizes: [
    {
      Name: "صغير",
      Size: "sm",
    },
    {
      Name: "متوسط",
      Size: "md",
    },
    {
      Name: "كبير",
      Size: "lg",
    },
  ],
  VALIDATION: {
    SELECT_FILE: "يرجى اختيار ملف",
    INVALID_NUMBER: "يرجى إدخال رقم صحيح",
  },
  FILTERS: {
    eq: "يساوي",
    ne: "لا يساوي",
    like: "يشبه",
    in: "ضمن",
    between: "بين",
    gt: "أكبر من",
    lt: "أقل من",
    gte: "أكبر من أو يساوي",
    lte: "أقل من أو يساوي",
    From: "من",
    To: "إلى",
  },
  // ============== Pages =================
  AUTH: {
    CARD_TITLE_SIGNIN: `تسجيل الدخول إلى ${APP_NAME}`,
    Method: "بريد إلكتروني أو رمز",
    PASSWORD: "كلمة المرور",
    SIGNIN_BUTTON: "تسجيل الدخول",
    SIGNIN_BUTTON_LOADING: "جارٍ تسجيل الدخول...",
    FORGOT_PASSWORD: "نسيت كلمة المرور؟",
    SIGNIN_SUCCESS: "تم تسجيل الدخول بنجاح",
    SIGNIN_ERROR: "فشل تسجيل الدخول، حاول مرة أخرى ببيانات صحيحة",
    ALREADY_HAVE_ACCOUNT: "لديك حساب بالفعل؟",
  },
  SIDEBAR: {
    LOGOUT: "تسجيل الخروج",
    Auth: "تسجيل الدخول",
    Landing: "الرئيسية",
    Dashboard: "لوحة التحكم",
    Nitch: "المجالات",
    Interest: "اهتمامات العملاء",
    ProductType: "نوع المنتج",
    ContactWay: "طرق التواصل",
    Platform: "منصات الليدز",
    Branch: "الفروع",
    Admin: "لوحة التحكم",
    Role: "الادوار",
    SubSectionSub: "الاقسام",
    Classification: "التصنيفات",
    Package: "الباقات",
    Section: "الاقسام",
    SubSection: "الاقسام",
    Status: "الحالات",
    User: "المستخدمين",
    Team: "الفرق",
    Customer: "العملاء",
    Contract: "العقود",
    Setting: "الاعدادات",
  },
  TABLES: {
    ACTIONS: {
      name: "الاجراءات",
      order: "Action",
      sort: "",
    },
    ID: {
      name: "المعرف",
      order: "ASC",
      sort: "{Col}Id",
    },
    PUBLIC: [
      {
        name: "الاسم",
        order: "ASC",
        sort: "{Col}Name",
        vaild: "{Col}Name",
      },
    ],
    CLASSIFICATION: [
      {
        name: "الاسم",
        order: "ASC",
        sort: "{Col}Name",
        vaild: "{Col}Name",
      },
      {
        name: "الكود",
        order: "ASC",
        sort: "{Col}Code",
        vaild: "{Col}Code",
      },
    ],
    ROLE: [
      {
        name: "الاسم",
        order: "ASC",
        sort: "{Col}Name",
        vaild: "{Col}Name",
      },
      {
        name: "الصلاحيات",
        order: "",
        sort: "{Col}Permission",
        vaild: "{Col}Permission",
      },
    ],
    SUB_SECTION_SUB: [
      {
        name: "الاسم",
        order: "ASC",
        sort: "{Col}Name",
        vaild: "SubSectionSubName",
      },
      {
        name: "الكود",
        order: "ASC",
        sort: "{Col}Key",
        vaild: "SubSectionSubKey",
      },
      {
        name: "القسم الرئيسي",
        order: "",
        sort: "Section",
        vaild: "Section",
      },
      {
        name: "القسم",
        order: "ASC",
        sort: "SubSectionId",
        vaild: "SubSectionId",
      },
    ],
    USER: [
      {
        name: "الاسم",
        order: "ASC",
        sort: "{Col}Name",
        vaild: "UserName",
      },
      {
        name: "الفريق",
        order: "ASC",
        sort: "{Col}TeamId",
        vaild: "UserTeamId",
      },
      {
        name: "الفرع",
        order: "ASC",
        sort: "{Col}BranchId",
        vaild: "UserBranchId",
      },
      {
        name: " الاتصال",
        order: "ASC",
        sort: "{Col}Socket",
        vaild: "UserSocket",
      },
      {
        name: "البريد الالكتروني",
        order: "ASC",
        sort: "{Col}Email",
        vaild: "UserEmail",
      },
      {
        name: "الشركة",
        order: "ASC",
        sort: "{Col}Company",
        vaild: "UserCompany",
      },
      {
        name: "المسمي الوظيفي",
        order: "ASC",
        sort: "{Col}JobTitle",
        vaild: "UserJobTitle",
      },
      {
        name: "الكود",
        order: "ASC",
        sort: "{Col}Code",
        vaild: "UserCode",
      },
      {
        name: "الحالة",
        order: "ASC",
        sort: "{Col}StatusId",
        vaild: "UserStatus",
      },
      {
        name: "الدور",
        order: "ASC",
        sort: "{Col}RoleId",
        vaild: "UserRole",
      },
      {
        name: "القسم الرئيسي",
        order: "ASC",
        sort: "{Col}SectionId",
        vaild: "UserSection",
      },
      {
        name: "القسم الفرعي",
        order: "ASC",
        sort: "{Col}SubSectionId",
        vaild: "UserSubSection",
      },
      {
        name: "القسم الفرعي 2",
        order: "ASC",
        sort: "{Col}SubSectionSubId",
        vaild: "UserSubSectionSub",
      },
      {
        name: "تاريخ الانشاء",
        order: "ASC",
        sort: "{Col}CreatedAt",
        vaild: "UserCreatedAt",
      },
    ],
    CUSTOMER: [
      {
        name: "اهتمامات العميل",
        order: "ASC",
        sort: "{Col}InterestId",
        vaild: "CustomerInterestId",
      },
      {
        name: "الموقف من الرد",
        order: "ASC",
        sort: "{Col}ResPosition",
        vaild: "CustomerResPosition",
      },
      {
        name: "المتابعة (Tele)",
        order: "ASC",
        sort: "{Col}FollowUpStatus",
        vaild: "CustomerFollowUpStatus",
      },
      {
        name: "تاريخ المتابعة (Tele)",
        order: "ASC",
        sort: "{Col}FollowUpDate",
        vaild: "CustomerFollowUpDate",
      },

      {
        name: "الاسم",
        order: "ASC",
        sort: "{Col}Name",
        vaild: "CustomerName",
        float: true,
      },
      {
        name: "مصدر الداتا",
        order: "ASC",
        sort: "{Col}DataSource",
        vaild: "CustomerDataSource",
      },
      {
        name: "الدولة",
        order: "ASC",
        sort: "{Col}Country",
        vaild: "CustomerCountry",
      },
      {
        name: "رقم الهاتف",
        order: "ASC",
        sort: "{Col}PhoneNumber",
        vaild: "CustomerPhoneNumber",
      },
      {
        name: "رقم الهاتف الثاني",
        order: "ASC",
        sort: "{Col}PhoneNumber2",
        vaild: "CustomerPhoneNumber2",
      },
      {
        name: "نوع العميل",
        order: "ASC",
        sort: "{Col}Type",
        vaild: "CustomerType",
      },
      {
        name: "العنوان",
        order: "ASC",
        sort: "{Col}Adress",
        vaild: "CustomerAdress",
      },
      {
        name: "البريد الالكتروني",
        order: "ASC",
        sort: "{Col}Email",
        vaild: "CustomerEmail",
      },
      {
        name: "رابط الموقع / المتجر",
        order: "ASC",
        sort: "{Col}Url",
        vaild: "CustomerUrl",
      },
      {
        name: "نوع الشركة / العمل",
        order: "ASC",
        sort: "{Col}WorkType",
        vaild: "CustomerWorkType",
      },
      {
        name: "نوع المنتج",
        order: "ASC",
        sort: "{Col}ProductTypeId",
        vaild: "CustomerProductTypeId",
      },
      {
        name: "حالة العميل في السوق",
        order: "ASC",
        sort: "{Col}Status",
        vaild: "CustomerStatus",
      },
      {
        name: "وسيلة التواصل",
        order: "ASC",
        sort: "{Col}ContactWayId",
        vaild: "CustomerContactWayId",
      },
      {
        name: "منصة الليدز",
        order: "ASC",
        sort: "{Col}LeedsPlatformId",
        vaild: "CustomerLeedsPlatformId",
      },
      {
        name: "تاريخ الانشاء",
        order: "ASC",
        sort: "{Col}CreatedAt",
        vaild: "CustomerCreatedAt",
      },
      {
        name: "تاريخ اخر تعديل",
        order: "ASC",
        sort: "{Col}UpdatedAt",
        vaild: "CustomerUpdatedAt",
      },
      {
        name: "تم الأنشاء بواسطة",
        order: "ASC",
        sort: "{Col}CreatedById",
        vaild: "CustomerCreatedById",
      },
      {
        name: "تم التعديل بواسطة",
        order: "ASC",
        sort: "{Col}UpdatedById",
        vaild: "CustomerUpdatedById",
      },
      {
        name: "المجال",
        order: "ASC",
        sort: "{Col}NitchId",
        vaild: "CustomerNitchId",
      },
      {
        name: "التصنيف",
        order: "ASC",
        sort: "{Col}ClassificationId",
        vaild: "CustomerClassificationId",
      },
    ],
    CONTRACT: [
      // Assocations
      {
        name: "الفرع",
        order: "ASC",
        sort: "{Col}BranchId",
        vaild: "ContractBranchId",
      },
      {
        name: "هيد الحسابات",
        order: "ASC",
        sort: "{Col}AccountMainId",
        vaild: "ContractAccountMainId",
      },
      {
        name: "هيد الاكونت مانجر",
        order: "ASC",
        sort: "{Col}AccountManagerMainId",
        vaild: "ContractAccountManagerMainId",
      },
      {
        name: "هيد التكنيكال",
        order: "ASC",
        sort: "{Col}TecnicalMainId",
        vaild: "ContractTecnicalMainId",
      },
      {
        name: "هيد الاقسام",
        order: "ASC",
        sort: "{Col}TecnicalSubMainId",
        vaild: "ContractTecnicalSubMainId",
      },
      {
        name: "التكنيكال تيم ليدر",
        order: "ASC",
        sort: "{Col}TecnicalTeamLeaderId",
        vaild: "ContractTecnicalTeamLeaderId",
      },
      {
        name: "ايجنت التكنيكال",
        order: "",
        sort: "{Col}Tecnical",
        vaild: "ContractTecnical",
      },
      {
        name: "المبيعات",
        order: "ASC",
        sort: "{Col}SalesId",
        vaild: "ContractSalesId",
      },
      {
        name: "الحسابات",
        order: "ASC",
        sort: "{Col}AccountId",
        vaild: "ContractAccountId",
      },
      {
        name: "الاكونت مانجر",
        order: "ASC",
        sort: "{Col}AccountManagerId",
        vaild: "ContractAccountManagerId",
      },
      {
        name: "تم الانشاء بواسطة",
        order: "ASC",
        sort: "{Col}CreatedById",
        vaild: "ContractCreatedById",
      },
      {
        name: "متابعة بواسطة",
        order: "ASC",
        sort: "{Col}TeleSalesId",
        vaild: "ContractTeleSalesId",
      },
      // Customer Data
      {
        name: "اسم العميل",
        order: "",
        sort: "{Col}CustomerName",
        vaild: "ContractCustomerName",
        float: true,
      },
      {
        name: "لينك العميل",
        order: "",
        sort: "{Col}CustomerUrl",
        vaild: "ContractCustomerUrl",
      },
      {
        name: "نوع العميل",
        order: "",
        sort: "{Col}CustomerType",
        vaild: "ContractCustomerType",
      },
      {
        name: "دولة العميل",
        order: "",
        sort: "{Col}CustomerCountry",
        vaild: "ContractCustomerCountry",
      },
      {
        name: "عنوان العميل",
        order: "",
        sort: "{Col}CustomerAdress",
        vaild: "ContractCustomerAdress",
      },
      // Other data
      {
        name: "تاريخ الانشاء",
        order: "ASC",
        sort: "{Col}CreatedAt",
        vaild: "ContractCreatedAt",
      },
      {
        name: "اخر تحديث",
        order: "ASC",
        sort: "{Col}UpdatedAt",
        vaild: "ContractUpdatedAt",
      },
      {
        name: "الاقسام التقنية",
        order: "ASC",
        sort: "{Col}TecnicalSections",
        vaild: "ContractTecnicalSections",
      },

      {
        name: "موعد مع المبيعات",
        order: "ASC",
        sort: "{Col}SalesDate",
        vaild: "ContractSalesDate",
      },
      {
        name: "تاريخ ادخال البيانات",
        order: "ASC",
        sort: "{Col}EntryDate",
        vaild: "ContractEntryDate",
      },
      {
        name: "اسم المهمة",
        order: "ASC",
        sort: "{Col}TaskName",
        vaild: "ContractTaskName",
      },
      {
        name: "المتابعة (Sales)",
        order: "ASC",
        sort: "{Col}StandUp",
        vaild: "ContractStandUp",
      },
      {
        name: "تاريخ المتابعة (Sales)",
        order: "ASC",
        sort: "{Col}StandUpDate",
        vaild: "ContractStandUpDate",
      },
      {
        name: "الفاتورة",
        order: "ASC",
        sort: "{Col}Invoice",
        vaild: "ContractInvoice",
      },
      {
        name: "تاريخ الدفع",
        order: "ASC",
        sort: "{Col}PayDate",
        vaild: "ContractPayDate",
      },
      {
        name: "المبلغ المدفوع",
        order: "ASC",
        sort: "{Col}Ammount",
        vaild: "ContractAmmount",
      },
      {
        name: "عدد الشهور المدفوعة",
        order: "ASC",
        sort: "{Col}PaidMonthes",
        vaild: "ContractPaidMonthes",
      },
      {
        name: "تاريخ التحويل للمبياعات",
        order: "ASC",
        sort: "{Col}TimeRecives",
        vaild: "ContractTimeRecives",
      },
      {
        name: "تاريخ بدء الخدمة",
        order: "ASC",
        sort: "{Col}ServiceStartDate",
        vaild: "ContractServiceStartDate",
      },
      {
        name: "الباقة",
        order: "ASC",
        sort: "{Col}PackageId",
        vaild: "ContractPackageId",
      },
      {
        name: "نوع العقد",
        order: "ASC",
        sort: "{Col}Type",
        vaild: "ContractType",
      },
      {
        name: "موقف الشهر القادم",
        order: "ASC",
        sort: "{Col}LastPosition",
        vaild: "ContractLastPosition",
      },
      {
        name: "تاريخ الموقف القادم",
        order: "ASC",
        sort: "{Col}LastPositionDate",
        vaild: "ContractLastPositionDate",
      },
      // Notes
      {
        name: "البريف النهائي للمبيعات",
        order: "",
        sort: "{Col}SalesPref",
        vaild: "ContractSalesPref",
      },
      {
        name: "ملاحظات تخص العميل",
        order: "",
        sort: "{Col}CustomarNote",
        vaild: "ContractCustomarNote",
      },
      {
        name: "بريف العميل النهائي",
        order: "",
        sort: "{Col}CustomarPref",
        vaild: "ContractCustomarPref",
      },
      {
        name: "فيدباك العميل",
        order: "",
        sort: "{Col}CustomarFeedback",
        vaild: "ContractCustomarFeedback",
      },
      {
        name: "بريف الاكونت مانجر",
        order: "",
        sort: "{Col}AccountManagerNote",
        vaild: "ContractAccountManagerNote",
      },
      {
        name: "بريف قائد السيو",
        order: "",
        sort: "{Col}TecnicalSeoTeamLeaderPref",
        vaild: "ContractTecnicalSeoTeamLeaderPref",
      },
      {
        name: "بريف قائد السوشيال",
        order: "",
        sort: "{Col}TecnicalSocialTeamLeaderPref",
        vaild: "ContractTecnicalSocialTeamLeaderPref",
      },
      {
        name: "بريف قائد الاعلانات",
        order: "",
        sort: "{Col}TecnicalAdsTeamLeaderPref",
        vaild: "ContractTecnicalAdsTeamLeaderPref",
      },
      {
        name: "بريف قائد الفرق الاخري",
        order: "",
        sort: "{Col}TecnicalOtherTeamLeaderPref",
        vaild: "ContractTecnicalOtherTeamLeaderPref",
      },
      {
        name: "بريف المدير التقني",
        order: "",
        sort: "{Col}TecnicalHeadPref",
        vaild: "ContractTecnicalHeadPref",
      },
      {
        name: "بريف رئيس القسم",
        order: "",
        sort: "{Col}TecnicalSectionHeadPref",
        vaild: "ContractTecnicalSectionHeadPref",
      },
    ],
  },
  FORMS: {
    Pending: "ابتدائي",
    Completed: "نهائي",
    OnProgress: "جاري العمل",
    Paid: "مدفوع",
    UnPaid: "غير مدفوع",
    Canceled: "ملغي",
    Company: "شركة",
    Personal: "شخصي",
    Data: "داتا",
    Lead: "ليد",
    ConvertOptions: [
      {
        label: "تلي سيلز",
        value: "TeleSales",
      },
      {
        label: "المبيعات",
        value: "Sales",
      },
      {
        label: "الاكونت مانجر",
        value: "AccountManager",
      },
      {
        label: "الحسابات",
        value: "Accounts",
      },
      {
        label: "التكنيكال",
        value: "Tecnical",
      },
    ],
    DataSource: [
      {
        label: "داتا",
        value: "Data",
      },
      {
        label: "ليد",
        value: "Lead",
      },
    ],
    Awnser: "رد",
    NoAwnser: "لا يوجد رد",
    CustomerSts: {
      gt: "اكتر من سنة", // لا يتم ترجمة هذه الكلمات
      lt: "اقل من سنة", // لا يتم ترجمة هذه الكلمات
    },
    Section: "القسم",
    // user -------------------------------------
    TeamName: "الاسم",
    UserName: "الاسم",
    UserBranch: "الفرع",
    UserBranchId: "الفرع",
    UserTeamId: "الفريق",
    UserJobTitle: "المسمي الوظيفي",
    UserEmail: "البريد الالكتروني",
    UserPassword: "كلمة المرور",
    OldPassword: "كلمة المرور القديمة",
    NewPassword: "كلمة المرور الجديدة",
    UserCode: "الكود",
    UserRole: "الدور",
    UserCreatedAt: "تاريخ الانشاء",
    UserStartDate: "تاريخ البدء",
    UserStatus: "الحالة",
    UserSection: "القسم الرئيسي",
    UserSubSection: "القسم الفرعي",
    UserSubSectionSub: "القسم الفرعي 2",
    NitchName: "الاسم",
    InterestName: "الاسم",
    ProductTypeName: "الاسم",
    ContactWayName: "الاسم",
    PlatformName: "الاسم",
    SectionName: "الاسم",
    StatusName: "الاسم",
    PackageName: "الاسم",
    SubSectionName: "الاسم",
    SubSectionKey: "المفتاح",
    SubSectionSectionId: "القسم الرئيسي",
    Method: "البريد الالكتروني او الكود",
    Password: "كلمة المرور",
    // ----------------- Customer -----------------
    CustomerDataSource: "مصدر الداتا",
    CustomerCountry: "الدولة",
    CustomerAdress: "العنوان",
    CustomerName: "اسم العميل",
    CustomerPhoneNumber: "رقم الهاتف",
    CustomerPhoneNumber2: "رقم الهاتف 2",
    CustomerEmail: "البريد الالكتروني",
    CustomerUrl: "رابط العميل",
    CustomerType: "نوع العميل",
    CustomerWorkType: "نوع الشركة / العمل",
    CustomerStatus: "حالة العميل في السوق",
    CustomerContactWayId: "وسيلة التواصل",
    CustomerLeedsPlatformId: "منصة الليدز",
    CustomerNitch: "المجال",
    CustomerNitchId: "المجال",
    CustomerClassification: "التصنيف",
    CustomerClassificationId: "التصنيف",
    CustomerUpdatedAt: "تاريخ اخر تعديل",
    CustomerCreatedAt: "تاريخ الانشاء",
    CustomerCreatedBy: "تم الانشاء بواسطة",
    CustomerUpdatedBy: "تم التعديل بواسطة",
    CustomerCreatedById: "تم الانشاء بواسطة",
    CustomerUpdatedById: "تم التعديل بواسطة",
    CustomerBranchId: "الفرع",
    CustomerBranch: "الفرع",
    CustomerProductTypeId: "نوع المنتج",
    CustomerProductType: "نوع المنتج",
    // New
    CustomerResPosition: "الموقف من الرد",
    CustomerFollowUpDate: "تاريخ المتابعة (Tele Sales)",
    CustomerFollowUpStatus: "المتابعة (Tele Sales)",
    CustomerInterestId: "اهتمامات العميل",

    //    Classification Data
    ClassificationName: "الاسم",
    ClassificationCode: "الكود",
    File: "الملف",
    //    Contract
    ContractSales: "المبيعات",
    // العميل
    ContractCustomerName: "اسم العميل",
    ContractCustomerUrl: "لينك العميل",
    ContractCustomerType: "نوع العميل",
    ContractCustomerCountry: "دولة العميل",
    ContractCustomerAdress: "عنوان العميل",

    ContractSalesDate: "موعد مع المبيعات",
    ContractEntryDate: "تاريخ ادخال البيانات",
    ContractTaskName: "اسم المهمة",
    //    contract Notes
    ContractSalesPref: "البريف النهائي للمبيعات",
    ContractCustomarNote: "ملاحظات تخص العميل",
    ContractCustomarFeedback: "فيدباك العميل",
    ContractCustomarPref: "بريف العميل النهائي",
    ContractAccountManagerNote: "بريف الاكونت مانجر",
    ContractTecnicalSeoTeamLeaderPref: "بريف قائد السيو",
    ContractTecnicalSocialTeamLeaderPref: "بريف قائد السوشيال",
    ContractTecnicalAdsTeamLeaderPref: "بريف قائد الاعلانات",
    ContractTecnicalOtherTeamLeaderPref: "بريف قائد الفرق الاخري",
    ContractTecnicalHeadPref: "بريف الرئيس التقني",
    //  Sales contract data
    ContractStandUp: "المتابعة (Sales)",
    ContractStandUpDate: "تاريخ المتابعة (Sales)",
    ContractInvoice: "فاتورة / العقد",
    ContractPayDate: "تاريخ الدفع",
    ContractAmmount: "المبلغ المدفوع",
    ContractPaidMonthes: "عدد الشهور المدفوعة",
    //  Another contract Data
    ContractTimeRecives: "تاريخ التحويل الي المبيعات",
    ContractServiceStartDate: "تاريخ بدء الخدمة",
    ContractPhoneNumber: "رقم الهاتف",
    ContractInvoiceLink: "رابط الفاتورة",
    ContractPackageId: "الباقة",
    ContractCreatedAt: "تاريخ الانشاء",
    ContractType: "نوع العقد",
    ContractTecnicalSections: "اقسام التكنيكال",
    // ContractHistory
    HistoryPosition: "موقف الشهر القادم",
    HistoryUpdate: "تحديث البينات",
    HistoryNewMsg: "سيتم انشاء موقف جديد.",
    HistoryUpdateMsg: "سيتم تحديث بينات اخر موقف متوفر",
    HistoryDate: "تاريخ الموقف",
    ContractNextMonthPosition: "موقف الشهر القادم",
    ContractNextMonthPositionDate: "تاريخ موقف الشهر القادم",
    ContractLastPosition: "موقف الشهر القادم",
    ContractLastPositionDate: "تاريخ موقف الشهر القادم",
    ContractUpdatedAt: "تاريخ اخر التحديث",

    ContractAccountMainId: "هيد الحسابات",
    ContractAccountManagerMainId: "هيد الاكونت مانجر",
    ContractTecnicalMainId: "هيد التكنيكال",
    ContractTecnicalSubMainId: "هيد الاقسام",
    ContractTecnicalTeamLeaderId: "التكنيكال تيم ليدر",
    ContractTecnical: "التكنيكال",
    ContractCreatedById: "تم الانشاء بواسطة",
    ContractTeleSalesId: "متابعة بواسطة",
    ContractSalesId: "المبيعات",
    ContractBranchId: "الفرع",
    ContractBranch: "الفرع",
    ContractAccountManagerId: "الاكونت مانجر",
    ContractAccountManager: "الاكونت مانجر",
    ContractTecnicalId: "التكنيكال",
    ContractAccountId: "الحسابات",
    ContractAccount: "الحسابات",
    ContractCustomerId: "العميل",
    // العميل
    //
    RolePermissions: "الصلاحيات",
    RoleName: "الاسم",
    Files: "الملف",
    Source: "النوع",
    //
    SubSectionSubName: "الاسم",
    SubSectionSubKey: "المفتاح",
    SubSectionId: "القسم الفرعي",
    SubSection: "القسم الفرعي",
    Seo: "السيو",
    Social: "سوشيال",
    Ads: "اعلانات",
    Other: "اخري",
    TecnicalHead: "الرئيس التقني",
    TecnicalTeamLeader: "مدير الفريق",
    TecnicalAgent: "الايجنت",
    Users: "المستخدمين",
    ConTaskName: "اسم المهمة",
    ConSubTaskValue: "وصف المهمة",
    ConTaskStart: "تاريخ البدء",
    ConTaskSection: "القسم",
    ConTaskEnd: " تاريخ الانتهاء",
    ConTaskCreatedBy: "تم الانشاء بواسطة",
    ConTaskIsCompleted: "حالة المهمة",
  },
  TABS: {
    CONTRACT: [
      {
        label: "المعلومات",
        value: "info",
      },
      {
        label: "المهام",
        value: "task",
      },
      {
        label: "الملفات",
        value: "doc",
      },
    ],
    UPLOAD: [
      {
        label: "ابتدائي",
        value: "Pending",
      },
      {
        label: "نهائي",
        value: "Finished",
      },
    ],
    CONTRACTYPEPLUS: [
      {
        label: "لا يوجد",
        value: "Progress",
      },
    ],
  },
  CALENDER: {
    MONTHES: [
      {
        Name: "يناير",
        Key: "January",
        Short: "Jan",
        Number: "1",
      },
      {
        Name: "فبراير",
        Key: "February",
        Short: "Feb",
        Number: "2",
      },
      {
        Name: "مارس",
        Key: "March",
        Short: "Mar",
        Number: "3",
      },
      {
        Name: "ابريل",
        Key: "April",
        Short: "Apr",
        Number: "4",
      },
      {
        Name: "مايو",
        Key: "May",
        Short: "May",
        Number: "5",
      },
      {
        Name: "يونيو",
        Key: "June",
        Short: "Jun",
        Number: "6",
      },
      {
        Name: "يوليو",
        Key: "July",
        Short: "Jul",
        Number: "7",
      },
      {
        Name: "اغسطس",
        Key: "August",
        Short: "Aug",
        Number: "8",
      },
      {
        Name: "سبتمبر",
        Key: "September",
        Short: "Sep",
        Number: "9",
      },
      {
        Name: "اكتوبر",
        Key: "October",
        Short: "Oct",
        Number: "10",
      },
      {
        Name: "نوفمبر",
        Key: "November",
        Short: "Nov",
        Number: "11",
      },
      {
        Name: "ديسمبر",
        Key: "December",
        Short: "Dec",
        Number: "12",
      },
    ],
  },
  LANDING: {
    HERO: {
      TITLE_1: APP_NAME,
      TITLE_2: "ادارة العملاء بسهولة",
      DESC: "تم الانشاء اليك خصيصا لتجعل عملك اسهل ",
      BTN: "تسجيل الدخول",
      BACK: "رجوع",
      LOGOUT: "تسجيل الخروج",
    },
  },
  PERMISSIONS: {
    "Permissions:All": "جميع الصلاحيات",
    "Customer:Create": "انشاء العملاء",
    "Customer:Read": "استعرض العملاء",
    "Customer:Update": "تحديث العملاء",
    "Customer:Delete": "حذف العملاء",
    "Customer:Export": "تصدير العملاء",
    "Customer:Import": "استيراد العملاء",
    "Customer:All": "جميع صلاحيات العملاء",
    "Contract:Create": "انشاء العقود",
    "Contract:Read": "استعرض العقود",
    "Contract:Update": "تحديث العقود",
    "Contract:Delete": "حذف العقود",
    "Contract:Upload": "رفع العقود",
    "Contract:Download": "تحميل العقود",
    "Contract:Export": "تصدير العقود",
    "Contract:Import": "استيراد العقود",
    "Contract:All": "جميع صلاحيات العقود",
  },
  UPLOAD_TYPES: [
    {
      Name: "عقد",
      Value: "Contract",
    },
    {
      Name: "فاتورة",
      Value: "Invoice",
    },
  ],
};
export default Language;
