const APP_NAME = "Future Solutions";
const Language = {
  APP_NAME: APP_NAME,
  NO_INTERNET: "No Internet Connection",
  CHECK_DATA: "Checking Data Please wait...",
  NEED_RELOGIN: "You need to relogin",
  NO_DATA: "No Data Founded",
  No_AGENTS: "No Agents For This Contract",
  PERPARING: "Preparing",
  PERPARE: "Prepare",
  READY: "Ready",
  ACTIONS: "Actions",
  SETTINGS: "Settings",
  CONVERT_DATA: "Convert Data",
  CANCEL: "Cancel",
  SAVE: "Save",
  ADD: "Add New",
  UPDATE: "Update",
  EDIT: "Edit",
  VERIFY: "Verify",
  DELETE: "Delete",
  CONFIRM: "Confirm",
  COMPLETE: "Complete",
  TASKS: "Sub Tasks",
  SHOW: "Show",
  SEARCH: "Search ...",
  SUCCESS: "Success",
  UPLOAD: "Upload Document",
  UP: "Upload",
  SYNC: "Synchronize Data",
  SYNCED: "Synchronized Data Successfully",
  DOWNLOAD: "Download",
  PRINT: "Print",
  EXPORT: "Export",
  REFRESH: "Refresh",
  FILTER: "Filter",
  DEV_TOOLS: "Context Menu Are Not Allowed",
  DELETE_CONFIRM:
    "Are You Sure You Want To Delete? \n You Can't Undo This Operation",
  CONFIM_MSG: "Are You Sure? This Is Important",
  VERIFY_CONFIRM: "Are You Sure? \n You Can't Undo This Operation",
  SERVER_ERROR: "Faild To Fetch Dua Server Error",
  CANCEL_DELETE: "Cancel Delete",
  LIMIT: "Limit",
  REDIRECT_AFTER: "Redirect To Main Page After {Seconds_replacer} Seconds",
  PAGINATION_1: "Page {page}  Of {total}  Pages",
  PAGINATION_2: "Show {count} From {total} Items",
  NO_FILE_PREVIEW: "Preview Not Allowed For This File Type Download It",
  NOTIFACTIONS: "Notifications",
  NOTIFACTION_MSG: "You Have New Notification",
  NO_PERMISSION: "You Don't Have Permission To Access This Page",
  NO_ANY_PERMISSION: "Your Role Can't Access Any Page Please Contact Admin",
  TYPE: "Type",
  NOTES: "Notes",
  PAGE_NOT_FOUND: "Page Not Found",
  BACK: "Back",
  Density: "Table Size",
  SELECTED: "Selected",
  CONTRACT_NOT_PAID: "You Need To Make Contract Paid Before Upload Contract",
  Sizes: [
    {
      Name: "Small",
      Size: "sm",
    },
    {
      Name: "Medium",
      Size: "md",
    },
    {
      Name: "Large",
      Size: "lg",
    },
  ],
  VALIDATION: {
    SELECT_FILE: "Please Select File",
    INVALID_NUMBER: "Please Enter Valid Number",
  },
  FILTERS: {
    eq: "Equal",
    ne: "Not Equal",
    like: "Like",
    in: "In",
    between: "Between",
    gt: "Greater Than",
    lt: "Less Than",
    gte: "Greater Than Equal",
    lte: "Less Than Equal",
    From: "From",
    To: "To",
  },
  // ============== Pages =================
  AUTH: {
    CARD_TITLE_SIGNIN: `Sign In to ${APP_NAME}`,
    Method: "Email Or Code",
    PASSWORD: "Password",
    SIGNIN_BUTTON: "Sign In",
    SIGNIN_BUTTON_LOADING: "Signing In...",
    FORGOT_PASSWORD: "Forgot Password?",
    SIGNIN_SUCCESS: "Sign In Successfully",
    SIGNIN_ERROR: "Failed to Sign In Try Again With ValidData",
    ALREADY_HAVE_ACCOUNT: "Already have an account?",
  },
  SIDEBAR: {
    LOGOUT: "Logout",
    Auth: "Login",
    Landing: "Home",
    Dashboard: "Dashboard",
    Nitch: "Nitch",
    Interest: "Interest",
    ProductType: "Product Type",
    ContactWay: "Contact Way",
    Platform: "Leeds Platform",
    Branch: "Branch",
    Role: "Role",
    Admin: "Administrator",
    SubSectionSub: "Section",
    Classification: "Classification",
    Package: "Package",
    Section: "Section",
    SubSection: "Section",
    Status: "Status",
    User: "Users",
    Team: "Teams",
    Customer: "Customer",
    Contract: "Contract",
    Setting: "Setting",
  },
  TABLES: {
    ACTIONS: {
      name: "Actions",
      order: "Action",
      sort: "",
    },
    ID: {
      name: "Id",
      order: "ASC",
      sort: "{Col}Id",
    },
    PUBLIC: [
      {
        name: "Name",
        order: "ASC",
        sort: "{Col}Name",
        vaild: "{Col}Name",
      },
    ],
    CLASSIFICATION: [
      {
        name: "Name",
        order: "ASC",
        sort: "{Col}Name",
        vaild: "{Col}Name",
      },
      {
        name: "Code",
        order: "ASC",
        sort: "{Col}Code",
        vaild: "{Col}Code",
      },
    ],
    ROLE: [
      {
        name: "Name",
        order: "ASC",
        sort: "{Col}Name",
        vaild: "{Col}Name",
      },
      {
        name: "Permissions",
        order: "",
        sort: "{Col}Permission",
        vaild: "{Col}Permission",
      },
    ],
    SUB_SECTION_SUB: [
      {
        name: "Name",
        order: "ASC",
        sort: "{Col}Name",
        vaild: "SubSectionSubName",
      },
      {
        name: "Key",
        order: "ASC",
        sort: "{Col}Key",
        vaild: "SubSectionSubKey",
      },
      {
        name: "Main Section",
        order: "",
        sort: "Section",
        vaild: "Section",
      },
      {
        name: "Section",
        order: "ASC",
        sort: "SubSectionId",
        vaild: "SubSectionId",
      },
    ],
    USER: [
      {
        name: "Name",
        order: "ASC",
        sort: "{Col}Name",
        vaild: "UserName",
      },
      {
        name: "Team",
        order: "ASC",
        sort: "{Col}TeamId",
        vaild: "UserTeamId",
      },
      {
        name: "Branch",
        order: "ASC",
        sort: "{Col}BranchId",
        vaild: "UserBranchId",
      },
      {
        name: "Connection",
        order: "ASC",
        sort: "{Col}Socket",
        vaild: "UserSocket",
      },
      {
        name: "Email",
        order: "ASC",
        sort: "{Col}Email",
        vaild: "UserEmail",
      },
      {
        name: "Company",
        order: "ASC",
        sort: "{Col}Company",
        vaild: "UserCompany",
      },
      {
        name: "Job Title",
        order: "ASC",
        sort: "{Col}JobTitle",
        vaild: "UserJobTitle",
      },
      {
        name: "Code",
        order: "ASC",
        sort: "{Col}Code",
        vaild: "UserCode",
      },
      {
        name: "Status",
        order: "ASC",
        sort: "{Col}StatusId",
        vaild: "UserStatus",
      },
      {
        name: "Role",
        order: "ASC",
        sort: "{Col}RoleId",
        vaild: "UserRole",
      },
      {
        name: "Section",
        order: "ASC",
        sort: "{Col}SectionId",
        vaild: "UserSection",
      },
      {
        name: "Section",
        order: "ASC",
        sort: "{Col}SubSectionId",
        vaild: "UserSubSection",
      },
      {
        name: "Sub Section",
        order: "ASC",
        sort: "{Col}SubSectionSubId",
        vaild: "UserSubSectionSub",
      },
      {
        name: "Created At",
        order: "ASC",
        sort: "{Col}CreatedAt",
        vaild: "UserCreatedAt",
      },
    ],
    CUSTOMER: [
      {
        name: "Customer Interest",
        order: "ASC",
        sort: "{Col}InterestId",
        vaild: "CustomerInterestId",
      },
      {
        name: "Response Position",
        order: "ASC",
        sort: "{Col}ResPosition",
        vaild: "CustomerResPosition",
      },
      {
        name: "Follow Up (Tele)",
        order: "ASC",
        sort: "{Col}FollowUpStatus",
        vaild: "CustomerFollowUpStatus",
      },
      {
        name: "Follow Up Date (Tele)",
        order: "ASC",
        sort: "{Col}FollowUpDate",
        vaild: "CustomerFollowUpDate",
      },

      {
        name: "Name",
        order: "ASC",
        sort: "{Col}Name",
        vaild: "CustomerName",
        float: true,
      },
      {
        name: "Data Source",
        order: "ASC",
        sort: "{Col}DataSource",
        vaild: "CustomerDataSource",
      },
      {
        name: "Country",
        order: "ASC",
        sort: "{Col}Country",
        vaild: "CustomerCountry",
      },
      {
        name: "Phone",
        order: "ASC",
        sort: "{Col}PhoneNumber",
        vaild: "CustomerPhoneNumber",
      },
      {
        name: "2nd Phone",
        order: "ASC",
        sort: "{Col}PhoneNumber2",
        vaild: "CustomerPhoneNumber2",
      },
      {
        name: "Type",
        order: "ASC",
        sort: "{Col}Type",
        vaild: "CustomerType",
      },
      {
        name: "Adress",
        order: "ASC",
        sort: "{Col}Adress",
        vaild: "CustomerAdress",
      },
      {
        name: "Email",
        order: "ASC",
        sort: "{Col}Email",
        vaild: "CustomerEmail",
      },
      {
        name: "Url",
        order: "ASC",
        sort: "{Col}Url",
        vaild: "CustomerUrl",
      },
      {
        name: "Work Type",
        order: "ASC",
        sort: "{Col}WorkType",
        vaild: "CustomerWorkType",
      },
      {
        name: "Product Type",
        order: "ASC",
        sort: "{Col}ProductTypeId",
        vaild: "CustomerProductTypeId",
      },
      {
        name: "Status",
        order: "ASC",
        sort: "{Col}Status",
        vaild: "CustomerStatus",
      },
      {
        name: "Contact Way",
        order: "ASC",
        sort: "{Col}ContactWayId",
        vaild: "CustomerContactWayId",
      },
      {
        name: "Leeds Platform",
        order: "ASC",
        sort: "{Col}LeedsPlatformId",
        vaild: "CustomerLeedsPlatformId",
      },
      {
        name: "Created At",
        order: "ASC",
        sort: "{Col}CreatedAt",
        vaild: "CustomerCreatedAt",
      },
      {
        name: "Updated At",
        order: "ASC",
        sort: "{Col}UpdatedAt",
        vaild: "CustomerUpdatedAt",
      },
      {
        name: "Created By",
        order: "ASC",
        sort: "{Col}CreatedById",
        vaild: "CustomerCreatedById",
      },
      {
        name: "Updated By",
        order: "ASC",
        sort: "{Col}UpdatedById",
        vaild: "CustomerUpdatedById",
      },
      {
        name: "Nitch",
        order: "ASC",
        sort: "{Col}NitchId",
        vaild: "CustomerNitchId",
      },
      {
        name: "Classification",
        order: "ASC",
        sort: "{Col}ClassificationId",
        vaild: "CustomerClassificationId",
      },
    ],
    CONTRACT: [
      // Assocations
      {
        name: "Branch",
        order: "ASC",
        sort: "{Col}BranchId",
        vaild: "ContractBranchId",
      },
      {
        name: "Head Accounts",
        order: "ASC",
        sort: "{Col}AccountMainId",
        vaild: "ContractAccountMainId",
      },
      {
        name: "Head Account Manager",
        order: "ASC",
        sort: "{Col}AccountManagerMainId",
        vaild: "ContractAccountManagerMainId",
      },
      {
        name: "Head Tecnical",
        order: "ASC",
        sort: "{Col}TecnicalMainId",
        vaild: "ContractTecnicalMainId",
      },
      {
        name: "Sections Head",
        order: "ASC",
        sort: "{Col}TecnicalSubMainId",
        vaild: "ContractTecnicalSubMainId",
      },
      {
        name: "Tecnical Team Leader",
        order: "ASC",
        sort: "{Col}TecnicalTeamLeaderId",
        vaild: "ContractTecnicalTeamLeaderId",
      },
      {
        name: "Tecnical",
        order: "",
        sort: "{Col}Tecnical",
        vaild: "ContractTecnical",
      },
      {
        name: "Sales",
        order: "ASC",
        sort: "{Col}SalesId",
        vaild: "ContractSalesId",
      },
      {
        name: "Account",
        order: "ASC",
        sort: "{Col}AccountId",
        vaild: "ContractAccountId",
      },
      {
        name: "Account Manager",
        order: "ASC",
        sort: "{Col}AccountManagerId",
        vaild: "ContractAccountManagerId",
      },
      {
        name: "Created By",
        order: "ASC",
        sort: "{Col}CreatedById",
        vaild: "ContractCreatedById",
      },
      {
        name: "Followed By",
        order: "ASC",
        sort: "{Col}TeleSalesId",
        vaild: "ContractTeleSalesId",
      },
      // Customer Data
      {
        name: "Customer Name",
        order: "",
        sort: "{Col}CustomerName",
        vaild: "ContractCustomerName",
        float: true,
      },
      {
        name: "Customer Url",
        order: "",
        sort: "{Col}CustomerUrl",
        vaild: "ContractCustomerUrl",
      },
      {
        name: "Customer Type",
        order: "",
        sort: "{Col}CustomerType",
        vaild: "ContractCustomerType",
      },
      {
        name: "Customer Country",
        order: "",
        sort: "{Col}CustomerCountry",
        vaild: "ContractCustomerCountry",
      },
      {
        name: "Customer Adress",
        order: "",
        sort: "{Col}CustomerAdress",
        vaild: "ContractCustomerAdress",
      },
      // Other data
      {
        name: "Created At",
        order: "ASC",
        sort: "{Col}CreatedAt",
        vaild: "ContractCreatedAt",
      },
      {
        name: "Updated At",
        order: "ASC",
        sort: "{Col}UpdatedAt",
        vaild: "ContractUpdatedAt",
      },
      {
        name: "Tecnical Sections",
        order: "ASC",
        sort: "{Col}TecnicalSections",
        vaild: "ContractTecnicalSections",
      },

      {
        name: "Sales Meeting Date",
        order: "ASC",
        sort: "{Col}SalesDate",
        vaild: "ContractSalesDate",
      },
      {
        name: "Entry Date",
        order: "ASC",
        sort: "{Col}EntryDate",
        vaild: "ContractEntryDate",
      },
      {
        name: "Task Name",
        order: "ASC",
        sort: "{Col}TaskName",
        vaild: "ContractTaskName",
      },
      {
        name: "Stand Up (Sales)",
        order: "ASC",
        sort: "{Col}StandUp",
        vaild: "ContractStandUp",
      },
      {
        name: "Stand Up Date (Sales)",
        order: "ASC",
        sort: "{Col}StandUpDate",
        vaild: "ContractStandUpDate",
      },

      {
        name: "Invoice",
        order: "ASC",
        sort: "{Col}Invoice",
        vaild: "ContractInvoice",
      },
      {
        name: "Pay Date",
        order: "ASC",
        sort: "{Col}PayDate",
        vaild: "ContractPayDate",
      },
      {
        name: "Ammount",
        order: "ASC",
        sort: "{Col}Ammount",
        vaild: "ContractAmmount",
      },
      {
        name: "Paid Monthes",
        order: "ASC",
        sort: "{Col}PaidMonthes",
        vaild: "ContractPaidMonthes",
      },
      {
        name: "Time Recives",
        order: "ASC",
        sort: "{Col}TimeRecives",
        vaild: "ContractTimeRecives",
      },
      {
        name: "Service Start Date",
        order: "ASC",
        sort: "{Col}ServiceStartDate",
        vaild: "ContractServiceStartDate",
      },
      {
        name: "Invoice Link",
        order: "ASC",
        sort: "{Col}InvoiceLink",
        vaild: "ContractInvoiceLink",
      },
      {
        name: "Package",
        order: "ASC",
        sort: "{Col}PackageId",
        vaild: "ContractPackageId",
      },
      {
        name: "Type",
        order: "ASC",
        sort: "{Col}Type",
        vaild: "ContractType",
      },
      {
        name: "Next Month Position",
        order: "ASC",
        sort: "{Col}LastPosition",
        vaild: "ContractLastPosition",
      },
      {
        name: "Next Month Position Date",
        order: "ASC",
        sort: "{Col}LastPositionDate",
        vaild: "ContractLastPositionDate",
      },
      // Notes
      {
        name: "Final Sales Pref",
        order: "",
        sort: "{Col}SalesPref",
        vaild: "ContractSalesPref",
      },
      {
        name: "Customar Note",
        order: "",
        sort: "{Col}CustomarNote",
        vaild: "ContractCustomarNote",
      },
      {
        name: "Final Customar Pref",
        order: "",
        sort: "{Col}CustomarPref",
        vaild: "ContractCustomarPref",
      },
      {
        name: "Customar Feedback",
        order: "",
        sort: "{Col}CustomarFeedback",
        vaild: "ContractCustomarFeedback",
      },
      {
        name: "Account Manager Pref",
        order: "",
        sort: "{Col}AccountManagerNote",
        vaild: "ContractAccountManagerNote",
      },
      {
        name: "Seo TeamLeader Pref",
        order: "",
        sort: "{Col}TecnicalSeoTeamLeaderPref",
        vaild: "ContractTecnicalSeoTeamLeaderPref",
      },
      {
        name: "Social TeamLeader Pref",
        order: "",
        sort: "{Col}TecnicalSocialTeamLeaderPref",
        vaild: "ContractTecnicalSocialTeamLeaderPref",
      },
      {
        name: "Ads TeamLeader Pref",
        order: "",
        sort: "{Col}TecnicalAdsTeamLeaderPref",
        vaild: "ContractTecnicalAdsTeamLeaderPref",
      },
      {
        name: "Other TeamLeader Pref",
        order: "",
        sort: "{Col}TecnicalOtherTeamLeaderPref",
        vaild: "ContractTecnicalOtherTeamLeaderPref",
      },
      {
        name: "Tecnical Head Note",
        order: "",
        sort: "{Col}TecnicalHeadPref",
        vaild: "ContractTecnicalHeadPref",
      },
      {
        name: "Section Head Note",
        order: "",
        sort: "{Col}TecnicalSectionHeadPref",
        vaild: "ContractTecnicalSectionHeadPref",
      },
    ],
  },
  FORMS: {
    Pending: "Pending",
    Completed: "Finished",
    OnProgress: "On Going",
    Paid: "Paid",
    UnPaid: "UnPaid",
    Canceled: "Canceled",
    Company: "Company",
    Personal: "Personal",
    Data: "Data",
    Lead: "Lead",
    ConvertOptions: [
      {
        label: "Tele Sales",
        value: "TeleSales",
      },
      {
        label: "Sales",
        value: "Sales",
      },
      {
        label: "AccountManager",
        value: "AccountManager",
      },
      {
        label: "Accounts",
        value: "Accounts",
      },
      {
        label: "Tecnical",
        value: "Tecnical",
      },
    ],
    DataSource: [
      {
        label: "Data",
        value: "Data",
      },
      {
        label: "Lead",
        value: "Lead",
      },
    ],
    Awnser: "Answer",
    NoAwnser: "No Answer",
    CustomerSts: {
      gt: "اكتر من سنة", // لا يتم ترجمة هذه الكلمات
      lt: "اقل من سنة", // لا يتم ترجمة هذه الكلمات
    },
    Section: "Section",
    // user -------------------------------------
    TeamName: "Name",
    UserName: "Name",
    UserBranch: "Branch",
    UserCreatedAt: "Created At",
    UserTeamId: "Team",
    UserBranchId: "Branch",
    UserJobTitle: "Job Title",
    UserEmail: "Email",
    UserPassword: "Password",
    OldPassword: "Old Password",
    NewPassword: "New Password",
    UserCode: "Code",
    UserRole: "Role",
    UserStartDate: "Start Date",
    UserStatus: "Status",
    UserSection: "Section",
    UserSubSection: "Sub Section",
    UserSubSectionSub: "Sub Section Sub",
    NitchName: "Name",
    InterestName: "Name",
    ProductTypeName: "Name",
    ContactWayName: "Name",
    PlatformName: "Name",

    BranchName: "Name",
    SectionName: "Name",
    StatusName: "Name",
    PackageName: "Name",
    SubSectionName: "Name",
    SubSectionKey: "Key",
    SubSectionSectionId: "Main Section",
    Method: "UserEmail Or UserCode",
    Password: "Password",
    // ----------------- Customer -----------------
    CustomerDataSource: "Data Source",
    CustomerCountry: "Country",
    CustomerAdress: "Adress",
    CustomerName: "Name",
    CustomerPhoneNumber: "Phone",
    CustomerPhoneNumber2: "2nd Phone",
    CustomerEmail: "Email",
    CustomerUrl: "Url",
    CustomerType: "Type",
    CustomerWorkType: "Work Type",
    CustomerStatus: "Status",
    CustomerContactWayId: "Contact Way",
    CustomerLeedsPlatformId: "Leeds Platform",
    CustomerNitch: "Nitch",
    CustomerNitchId: "Nitch",
    CustomerClassification: "Classification",
    CustomerClassificationId: "Classification",
    CustomerUpdatedAt: "Updated At",
    CustomerCreatedAt: "Created At",
    CustomerCreatedBy: "Created By",
    CustomerUpdatedBy: "Updated By",
    CustomerCreatedById: "Created By",
    CustomerUpdatedById: "Updated By",
    CustomerBranchId: "Branch",
    CustomerBranch: "Branch",
    CustomerProductTypeId: "Product Type",
    CustomerProductType: "Product Type",

    CustomerResPosition: "Response",
    CustomerFollowUpDate: "Follow Up Date (Tele)",
    CustomerFollowUpStatus: "Follow Up (Tele)",
    CustomerInterestId: "Customer Interest",

    //    Classification Data
    ClassificationName: "Name",
    ClassificationCode: "Code",
    File: "File",
    //    Contract
    ContractSales: "Sales",

    ContractCustomerName: "Customer Name",
    ContractCustomerUrl: "Customer Url",
    ContractCustomerType: "Customer Type",
    ContractCustomerCountry: "Customer Country",
    ContractCustomerAdress: "Customer Adress",
    ContractSalesDate: "Sales Meeting Date",
    ContractEntryDate: "Entry Date",
    ContractTaskName: "Task Name",
    //    contract Notes
    ContractSalesPref: "Final Sales Pref",
    ContractCustomarNote: "Customar Note",
    ContractCustomarFeedback: "Customar Feedback",
    ContractCustomarPref: "Final Customar Pref",
    ContractAccountManagerNote: "Account Manager Pref",
    ContractTecnicalSeoTeamLeaderPref: "Seo TeamLeader Pref",
    ContractTecnicalSocialTeamLeaderPref: "Social TeamLeader Pref",
    ContractTecnicalAdsTeamLeaderPref: "Ads TeamLeader Pref",
    ContractTecnicalOtherTeamLeaderPref: "Other TeamLeader Pref",
    ContractTecnicalHeadPref: "Tecnical Head Pref",
    ContractTecnicalSectionHeadPref: "Section Head Pref",
    //  Sales contract data
    ContractStandUp: "Stand Up (Sales)",
    ContractStandUpDate: "Stand Up Date (Sales)",
    ContractInvoice: "Invoice",
    ContractPayDate: "Pay Date",
    ContractAmmount: "Ammount",
    ContractPaidMonthes: "Paid Monthes",
    //  Another contract Data
    ContractTimeRecives: "Time Recives",
    ContractServiceStartDate: "Service Start Date",
    ContractPhoneNumber: "Phone Number",
    ContractInvoiceLink: "Invoice Link",
    ContractPackageId: "Package",
    ContractCreatedAt: "Created At",
    ContractType: "Type",
    ContractTecnicalSections: "Tecnical Sections",
    HistoryPosition: "Position",
    HistoryUpdate: "Update",
    HistoryNewMsg: "A New Position Will Be Created.",
    HistoryUpdateMsg: "The Last Position Will Be Updated.",
    HistoryDate: "Date",
    ContractNextMonthPosition: "Next Month Position",
    ContractLastPosition: "Next Month Position",
    ContractLastPositionDate: "Next Month Position Date",
    ContractNextMonthPositionDate: "Next Month Position Date",
    ContractUpdatedAt: "Updated At",
    ContractAccountMainId: "Head Accounts",
    ContractAccountManagerMainId: "Head Account Manager",
    ContractTecnicalMainId: "Head Tecnical",
    ContractTecnicalSubMainId: "Sections Head",
    ContractTecnicalTeamLeaderId: "Tecnical Team Leader",
    ContractTecnical: "Tecnical",
    ContractCreatedById: "Created By",
    ContractTeleSalesId: "Followed By",
    ContractBranch: "Branch",
    ContractBranchId: "Branch",
    ContractSalesId: "Sales",
    ContractAccountManagerId: "Account Manager",
    ContractAccountManager: "Account Manager",
    ContractTecnicalId: "Tecnical",
    ContractAccountId: "Accounts",
    ContractAccount: "Accounts",
    ContractCustomerId: "Customer",
    RolePermissions: "Permissions",
    RoleName: "Name",
    Files: "File",
    Source: "Type",
    SubSectionSubName: "Name",
    SubSectionSubKey: "Key",
    SubSectionId: "Sub Section",
    SubSection: "Sub Section",
    Seo: "Seo",
    Social: "Social",
    Ads: "Ads",
    Other: "Other",
    TecnicalHead: "Head",
    TecnicalTeamLeader: "Team Leader",
    TecnicalAgent: "Agent",
    Users: "Users",
    ConTaskName: "Name",
    ConSubTaskValue: "Description",
    ConTaskStart: "Start Date",
    ConTaskSection: "Section",
    ConTaskEnd: " End Date",
    ConTaskCreatedBy: "Created By",
    ConTaskIsCompleted: "Progress",
  },
  TABS: {
    CONTRACT: [
      {
        label: "Information",
        value: "info",
      },
      {
        label: "Tasks",
        value: "task",
      },
      {
        label: "Documents",
        value: "doc",
      },
    ],
    UPLOAD: [
      {
        label: "Pending",
        value: "Pending",
      },
      {
        label: "Finished",
        value: "Finished",
      },
    ],
    CONTRACTYPEPLUS: [
      {
        label: "No Type",
        value: "Progress",
      },
    ],
  },
  CALENDER: {
    MONTHES: [
      {
        Name: "January",
        Key: "January",
        Short: "Jan",
        Number: "1",
      },
      {
        Name: "February",
        Key: "February",
        Short: "Feb",
        Number: "2",
      },
      {
        Name: "March",
        Key: "March",
        Short: "Mar",
        Number: "3",
      },
      {
        Name: "April",
        Key: "April",
        Short: "Apr",
        Number: "4",
      },
      {
        Name: "May",
        Key: "May",
        Short: "May",
        Number: "5",
      },
      {
        Name: "June",
        Key: "June",
        Short: "Jun",
        Number: "6",
      },
      {
        Name: "July",
        Key: "July",
        Short: "Jul",
        Number: "7",
      },
      {
        Name: "August",
        Key: "August",
        Short: "Aug",
        Number: "8",
      },
      {
        Name: "September",
        Key: "September",
        Short: "Sep",
        Number: "9",
      },
      {
        Name: "October",
        Key: "October",
        Short: "Oct",
        Number: "10",
      },
      {
        Name: "November",
        Key: "November",
        Short: "Nov",
        Number: "11",
      },
      {
        Name: "December",
        Key: "December",
        Short: "Dec",
        Number: "12",
      },
    ],
  },
  LANDING: {
    HERO: {
      TITLE_1: APP_NAME,
      TITLE_2: "Customers Is Easy",
      DESC: "Crm Made For You, For Your Team",
      BTN: "Login",
      BACK: "Back",
      LOGOUT: "Log Out",
    },
  },
  PERMISSIONS: {
    "Permissions:All": "All Permissions",
    "Customer:Create": "Create Customer",
    "Customer:Read": "Read Customer",
    "Customer:Update": "Update Customer",
    "Customer:Delete": "Delete Customer",
    "Customer:Export": "Export Customer",
    "Customer:Import": "Import Customer",
    "Customer:All": "All Customer Permissions",
    "Contract:Create": "Create Contract",
    "Contract:Read": "Read Contract",
    "Contract:Update": "Update Contract",
    "Contract:Delete": "Delete Contract",
    "Contract:Upload": "Upload Contract",
    "Contract:Download": "Download Contract",
    "Contract:Export": "Export Contract",
    "Contract:Import": "Import Contract",
    "Contract:All": "All Contract Permissions",
  },
  UPLOAD_TYPES: [
    {
      Name: "Contract",
      Value: "Contract",
    },
    {
      Name: "Invoice",
      Value: "Invoice",
    },
  ],
};
export default Language;
